fix yaml syntax

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -28,6 +28,15 @@ jobs:
             exit 1
           fi
 
+      - name: Check DevOps keyword
+        run: |
+          if grep -qi "devops" app.txt; then
+            echo "DevOps is present ✅"
+          else
+            echo "DevOps not found ❌"
+            exit 1
+          fi
+
       - name: Show file content
         run: cat app.txt
 
@@ -45,11 +54,3 @@ jobs:
           else
             echo "Enough content ✅"
           fi
-       - name: Check DevOps keyword
-  run: |
-    if grep -q "DevOps" app.txt; then
-      echo "DevOps is present ✅"
-    else
-      echo "DevOps not found ❌"
-      exit 1
-    fi
