multiple job workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -10,14 +10,14 @@ steps:
   - name: checkout code
     uses: actions/checkout@v3
 
-- name: check file exists
-  run: |
-    if [ -f app.txt ]; then
-      echo "file exists"
-    else
-      echo "File missing"
-      exit 1
-    fi
+  - name: check file exists
+    run: |
+      if [ -f app.txt ]; then
+        echo "file exists"
+      else
+        echo "File missing"
+        exit 1
+      fi
 
 second-job:
   needs: check-file
