multiple job workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -6,23 +6,23 @@ jobs:
   check-file:
     runs-on: ubuntu-latest
 
-steps:
-  - name: checkout code
-    uses: actions/checkout@v3
+    steps:
+      - name: checkout code
+        uses: actions/checkout@v3
 
-  - name: check file exists
-    run: |
-      if [ -f app.txt ]; then
-        echo "file exists"
-      else
-        echo "File missing"
-        exit 1
-      fi
+      - name: check file exists
+        run: |
+          if [ -f app.txt ]; then
+            echo "file exists"
+          else
+            echo "File missing"
+            exit 1
+          fi
 
-second-job:
-  needs: check-file
-  runs-on: ubuntu-latest
+  second-job:
+    needs: check-file
+    runs-on: ubuntu-latest
 
-steps:
-  - name: Second job message
-    run: echo "Second job running"
+    steps:
+      - name: Second job message
+        run: echo "Second job running"
