check DevOps keyword

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -45,11 +45,11 @@ jobs:
           else
             echo "Enough content ✅"
           fi
-       -name: Check devOps keyword
-        run : |
-             if grep -q "DevOps" app.txt; then
-             echo "DevOps is present"
-             else
-             echo "DevOps not found"
-             exit 1
-          fi
+       - name: Check DevOps keyword
+  run: |
+    if grep -q "DevOps" app.txt; then
+      echo "DevOps is present ✅"
+    else
+      echo "DevOps not found ❌"
+      exit 1
+    fi
