multiple job workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -3,26 +3,26 @@ name: Multi Line Workflow
 on: [push]
 
 jobs:
-check-file:
-runs-on: ubuntu-latest
+  check-file:
+    runs-on: ubuntu-latest
 
 steps:
-- name: checkout code
-uses: actions/checkout@v3
+  - name: checkout code
+    uses: actions/checkout@v3
 
 - name: check file exists
-run: |
-if [ -f app.txt ]; then
-echo "file exists"
-else
-echo "File missing"
-exit 1
-fi
+  run: |
+    if [ -f app.txt ]; then
+      echo "file exists"
+    else
+      echo "File missing"
+      exit 1
+    fi
 
 second-job:
-needs: check-file
-runs-on: ubuntu-latest
+  needs: check-file
+  runs-on: ubuntu-latest
 
 steps:
-- name: Second job message
-run: echo "Second job running"
+  - name: Second job message
+    run: echo "Second job running"
